---
- name: Collect facts about system services
  service_facts:
  register: services_state

- name: Debug services
  debug:
    var: services_state

- name: Start services
  service:
    name: "{{ item.name }}"
    enabled: true
    state: started
  loop: "{{ services_state.ansible_facts.services|dict2items }}"
