---
- name: Install apache2
  package:
    name: apache2
    state: present

- name: Collect facts about system services
  service_facts:
  register: services_state

- name: Debug services
  debug:
    var: services_state

- name: Start services
  service:
    name: "{{ item.key }}"
    enabled: true
    state: started
  loop: "{{ services_state.ansible_facts.services|dict2items }}"

- name: Find services
  find:
    paths: /etc/systemd/system
    patterns: '*.service'
  register: found_services

- name: Display services
  debug:
    msg: "{{ found_services }}"
